name: "Release"

on:
  push:
    branches: [main]
    paths: ["version.py"]

jobs:
  build-and-release:
    name: "Build and Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: build
        run: |
          pip install wheel
          pip install build
          pip install .
          python setup.py sdist bdist_wheel --universal

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.API_TOKEN_ALL }}
          skip_existing: false
